import Head from "next/head";
import Navbar from "@/components/LandingPage/Navbar";
import Banner from "@/components/LandingPage/Banner";
import UsersInfo from "@/components/LandingPage/UsersInfo";
import WhyUs from "@/components/LandingPage/WhyUs";
import WhyAbroad from "@/components/LandingPage/WhyAbroad";
import Testimonials from "@/components/LandingPage/Testimonials";
import { Footer } from "@/components/LandingPage/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Formula gray</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/formulargray_03.png" />
      </Head>
      <div className=" fixed w-full  z-50 ">
        <Navbar />
      </div>
      <div className=" bg-white h-screen  ">
        <Banner />
        <UsersInfo />
        <WhyUs />
        <WhyAbroad />
        <Testimonials />
        <Footer />
      </div>
    </>
  );
}
